language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - "cpanm -n Mojolicious && cpanm -n Mango && cpanm -n Data::Printer && cpanm -n JSON && cpanm -n Bio::SeqIO"