language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - "cpanm --notest Mojolicious && cpanm --notest Mango && cpanm --notest Data::Printer && cpanm --notest JSON && cpanm --notest Bio::SeqIO"